### ISSUE TITLE
Game runs, clock does not.

### ISSUE THREAD

**Issue by Chase-san** [LordxOsmosisx86/DMG-KGDU-10-Plus-FRAM-Upgraded-PCB#2]
BOM

- 1x FM18W08-SG 
- 1x DMG-KGDU-10+, from JLCPCB
- 1x 771-LVC1G32GV125
- 5x 187-CL10B104KO8NNNC 
- 2x 187-CL10C150JB8NNNC 
- 1x 603-RC0603FR-07330KL 
- 1x 603-RC0603FR-0710KL 
- 1x 603-RC0603FR-071KL 
- 1x 603-AC0603JR-070RL 
- 1x 520-S-.32712.513XC
- 1x 712-BAT-HLD-002-SMT 
- 1x 658-CR2025 (Panasonic)
- 1x MX23C1603 (DMG-AAXE-0), from silver cart
- 1x BA6735, from silver cart
- 1x MBC3-B, from silver cart

Each part was placed in groups, meaning only one type of 0603 was loose at a time to prevent mixups. All work was performed on an ESD mat.

Game runs, clock does not. Any thoughts? I have other Ram Protect ICs and a few MBC3-As around.

Normal Images
![20230111_195631](https://user-images.githubusercontent.com/34535/211950791-9dd6abfe-4a92-4c98-8f33-e8ce6d858ef5.jpg)
![20230111_195641](https://user-images.githubusercontent.com/34535/211950797-b6a25a21-82f7-4f25-8516-32bed1f8f07e.jpg)

UV Images
![20230111_195658](https://user-images.githubusercontent.com/34535/211950800-89f28ed0-2a76-4094-86c4-443781d97309.jpg)
![20230111_195712](https://user-images.githubusercontent.com/34535/211950806-e3b1494b-03d1-4a9b-93d6-82e4b2a5f05f.jpg)

**Comment by Chase-san** [comment]
To be honest, the clock didn't wok BEFORE this either, this was something of a hail mary to fix it.

**Comment by Mhouranix1125** [comment]
@Chase-san  Hey man. Very good job putting it together. 

So the one thing I know that will stop thr clock is if you didn't put copper tape on the giant circle pad under the battery holder. Alternatively you could solder in a small nickel strip. This happens because the battery pad is slightly indented into the board. Same thing happened to me. I've since got it running on my gold silver and crystal versions. Let me know how it goes.

P.S: use a multimeter to test if you're getting the proper 3.3 volts by probing the top of the battery retainer and the right-most pin on the cart bus (ground pin)

**Comment by Chase-san** [comment]
I tested the battery with a multimeter and I am getting voltage, however I do have some copper tape.

The clock does not work IN or OUT of game.

**Comment by Mhouranix1125** [comment]
@Chase-san 

I see. And you're saying the clock did not run on your original OEM pcb?

Here is what I would do. Ensure your 15pf capacitors are properly placed. Reflow them and make doubly sure they're solid. 

Definitely place that copper tape before mounting the battery retainer for added security. 

If you're using the same reset protection IC and MBC3 from the OEM board that was giving you problems, replace ONE component at a time with a separate and known working one to rule out the bad component if there is one. I would start by replacing the protection IC first, and if the issue persists, replace the MBC3. 

In my original case, the thing that had stopped my clock from working was the lack of copper tape. Currently all my HDR flash carts as well as these are all working in proper form. I'm going to review the list of materials you purchased and compare them against what I'm using myself.

**Comment by Chase-san** [comment]
I replaced the Protection IC and the MBC3 on the original board to no effect (stolen from Mary Kate Pocket Planner). I DO have a working copy of silver, but I loathe the idea of poking at it or taking it's parts.

However I placed the tape and it appears the same still (I used a CR2016 holder, which holds the CR2025 very tightly, the tape makes it a tiny bit harder to insert).

The main differences are the battery holder (712-BAT-HLD-002-SMT) and the crystal (520-S-.32712.513XC), the rest 'should' be identical to your list.

I will check/replace those parts and let you know.

**Comment by Mhouranix1125** [comment]
If your battery is giving you voltage across the board then that should be fine. The specs for your rtc crystal seem similar enough with the only real difference I see being the series (R26 on mine). 

Humor me. Don't take your working silver completely apart. I just want you to borrow the crystal oscillator from the inside of it and try it out. Let's rule out all potential issues. (I do still have to go through your full list)

ALSO!! If that does end up being the culprit. Try one of your new oscillators on the working silver cart. I've had a few bad oscillators in a lot that I bought before.

**Comment by Chase-san** [comment]
1. Still no time however with just the capacitor reflow. Thought removing the battery causes a time jump.

2. Replaced the Protection IC, noticed a some solder under it from my paste, whoops. Still not working though.

3. I swapped the crystals between the working silver and the f-rom silver. They both operate as they did (working one works, f-rom does not), I'll just keep the new crystal in the working one for now (removing the battery every time is a PITA). The original crystal has printing on it, where as the ones I bought do not, so unlikely I mixed these up during the swap. R26 is just referring the size I think (2mm x 6mm), which my crystal is.

... All that is really left is the ROM, which doesn't make sense to me, and the MBC which I have changed before. I'll try the MBC again, but probably tomorrow.

EDIT: I do have a copy of crystal with a slightly more traditional F-ROM mod, where the clock works in game but not out of game. I will switch that over to this as well, but I am waiting for the OshPark boards for that.

**Comment by Mhouranix1125** [comment]
@Chase-san 

Hmm. Everything should work here. The oscillator works in the original cart so that's good. The battery retainer causing the battery to mount tightly into the board may cause issues. It's a long shot though. Could just be grasping at straws. Why not try a properly sized CR2016 battery. It could be mounting pressure. 

I would also reflow and make sure to press down a little on the top section of pins on the mbc3.

And It may just be me but I'm looking at the pictures you posted and why does it look like there are some broken traces above the mounting pads for the rtc crystal? Am I crazy or do those look cut?

If you'd like we can jump on a discord call as well while we troubleshoot this sometime. I'd love to see this workout for you.

**Comment by Mhouranix1125** [comment]
Sent. I'm on right now. If you want we can have a quick chat.

**Comment by Mhouranix1125** [comment]
The issue is solved. User had a few cold solder joints. The clock is now running.
